version: '3'
services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ADMIN_USERNAME} 
      MONGO_INITDB_ROOT_PASSWORD: ${ADMIN_PASSWORD}
      MONGO_INITDB_DATABASE: db
    expose:
      - 27017
    networks:
      - omniboard

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ADMIN_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
    - 8081:8081
    networks:
      - omniboard 
    depends_on:
      - mongo

  omniboard:
    image: vivekratnavel/omniboard:latest
    command: ["--mu", "mongodb://${ADMIN_USERNAME}:${ADMIN_PASSWORD}@mongo:27017/db?authSource=admin"]
    ports:
      - 9000:9000
    networks:
      - omniboard
    depends_on:
      - mongo


networks:
  omniboard: